[package]
name = "flappy_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[dependencies]
ggez = "0.9.3"
rand = "0.8.5"

[features]
console = []